# example docker-compose
version: "2"
services:
  node:
    container_name: discordgiveawaybot
    image: shukriadams/discord-giveawaybot:latest
    restart: unless-stopped
    command: npm start
    volumes:
    - ./discord-giveawaybot/:/usr/giveawaybot/discord-giveawaybot/:rw
